Update compose files to use new sf-cam images.
innovatrics/smartface pull request #109
Opened 2021-10-04 13:05 UTC by Temppus

2021-10-04 13:07 UTC, blaskoa approved these changes

2021-10-04 13:10 UTC, blaskoa requested changes
Maybe we should also change versions in `.env` file, so that even in the `dev` branch the docker-compose files are valid... on the other hand that would also require the release of SF with separate camera images which should be 4.11

2021-11-22 10:46 UTC, marek-nereca commented
> 



> Maybe we should also change versions in `.env` file, so that even in the `dev` branch the docker-compose files are valid... on the other hand that would also require the release of SF with separate camera images which should be 4.11

We could use internal notation with buildnumber

2021-12-06 14:10 UTC, blaskoa approved these changes

2021-12-06 15:44 UTC, merged